export const ROLES = {
  SYSTEM_ADMIN: 'SYSTEM_ADMIN',
  COMPANY_ADMIN: 'COMPANY_ADMIN',
  MANAGER: 'MANAGER',
  EMPLOYEE: 'EMPLOYEE',
} as const;

export const SALARY_STATUS = {
  DRAFT: 'DRAFT',
  CONFIRMED: 'CONFIRMED',
  PAID: 'PAID',
  FAILED: 'FAILED',
  SKIPPED: 'SKIPPED',
} as const;

export const INSURANCE_MODE = {
  AUTO: 'AUTO',
  MANUAL: 'MANUAL',
  NONE: 'NONE',
} as const;

export const LAYOUT = {
  SIDEBAR_WIDTH: 240,
  SIDEBAR_COLLAPSED_WIDTH: 64,
  TOPBAR_HEIGHT: 56,
  MOBILE_TOPBAR_HEIGHT: 48,
  MOBILE_TABBAR_HEIGHT: 56,
  CONTENT_MAX_WIDTH: 1280,
  CONTENT_PADDING: 32,
} as const;
